export const workouts = [
  {
    id: 1,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '1. Supino reto halteres comb',
    foco: ['Peitoral', 'Tríceps', 'Ombros'],
    series: 4,
    repeticoes: 12,
    carga: '10 kg cada mão',
    imagem: {
      src: '../../assets/supino-reto-halteres.jpg',
      alt: 'Supino reto halteres comb',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/SWVO95XzxKg' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 2,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '2. Supino inclinado halteres comb',
    foco: ['Peitoral', 'Tríceps', 'Ombros'],
    series: 4,
    repeticoes: 12,
    carga: '10 kg cada mão',
    imagem: {
      src: '../../assets/supino-inclinado-com-halteres.webp',
      alt: 'Supino inclinado halteres',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/F4Q1g2z8MWM' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 3,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '3. Flexão de braço',
    foco: ['Peitoral', 'Tríceps', 'Ombros'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/flexao-de-braço.webp',
      alt: 'Flexão de braço',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/lkvSelJ0tQ8' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: 'Combinado com inclinado',
  },
  {
    id: 4,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '4. Crucifixo polia baixa simultaneo',
    foco: ['Peitoral'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/crucifixo-polia-baixa.jpg',
      alt: 'Crucifixo polia baixa',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/jRz4GCdThm0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 5,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '5. Desenvolv. halteres aberto comb',
    foco: ['Ombros', 'Tríceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/desenvolvimento-halteres.jpg',
      alt: 'Desenvolv. halteres aberto',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/Z1KPdjNng8c' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 6,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '6. Elevação lateral halteres banco incl',
    foco: ['Ombros'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/elevação-lateral-halteres-banco-inclinado.jpg',
      alt: 'Elevação lateral halteres banco incl',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/8s9JRhE95mU' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 7,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '7. Tríceps testa barra w',
    foco: ['Tríceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/Tríceps-testa-barra-w.jfif',
      alt: 'Tríceps testa barra w',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/cAzPXrCBxWY' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 8,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '8. Tríceps coice polia',
    foco: ['Tríceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/Tríceps-coice-polia.webp',
      alt: 'Tríceps coice polia',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/qkuOPCJcYtE' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 9,
    treino: 'Peitoral e Tríceps',
    nome: 'Treino 1A',
    exercicio: '9. Esteira',
    foco: ['Aeróbico'],
    series: 0,
    repeticoes: 0,
    carga: '10 minutos',
    imagem: {
      src: '',
      alt: '',
    },
    video: '',
    obs: '',
  },
  {
    id: 10,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '2. Puxada alta barra romana frente',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/puxada-alta-barra-romana-frente.jfif',
      alt: 'Puxada alta barra romana frente',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/d-h0QELfY98' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 11,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '3. Remada curvada barra supinada',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/remada-curvada-supinada.jpg',
      alt: 'Remada curvada barra supinada',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/TD00shuX6hA' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 12,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '4. Remada cavalinho',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/remada-cavalinho.webp',
      alt: 'Remada cavalinho',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/TRqQamJvKY8' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 13,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '5. Remada unilateral',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/remada-unilateral.jpg',
      alt: 'Remada unilateral',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/EUisRaNkCd4' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 14,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '6. Rosca direta barra w 21',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-direta-barra-w-21.webp',
      alt: 'Rosca direta barra w 21',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/zBCiD2OzMPA' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 15,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '7. Rosca halteres combinada',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-halteres-combinada.webp',
      alt: 'Rosca halteres combinada',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/5XaJD_00mR0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 16,
    treino: 'Costas e Bíceps',
    nome: 'Treino 1B',
    exercicio: '8. Rosca polia alta simultanea',
    foco: [],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-polia-alta-simultanea.jpg',
      alt: 'Rosca polia alta simultanea',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/IBpCquCRohE' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 17,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '1. Esteira',
    foco: ['Aeróbico'],
    series: 0,
    repeticoes: 0,
    carga: '15 minutos',
    imagem: {
      src: '',
      alt: '',
    },
    video: '',
    obs: '',
  },
  {
    id: 18,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '2. Puxada alta aberta frente',
    foco: ['Costas'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/puxada-alta-aberta-frente.jpg',
      alt: 'Puxada alta aberta frente',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/BOW9my4J_ek' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 19,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '3. Puxada alta triangulo',
    foco: ['Costas'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/puxada-alta-triangulo.webp',
      alt: 'Puxada alta triangulo',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/uAnrJBnxrZ0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 20,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '4. Remada maquina fechada',
    foco: ['Costas'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/remada-maquina-fechada.webp',
      alt: 'Remada maquina fechada',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/t7qEY6_gM2E' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 21,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '5. Remada alta anilha',
    foco: ['Costas'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/remada-alta-anilha.jpg',
      alt: 'Remada alta anilha',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/RY2p9jhfBig' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 22,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '6. Rosca maquina',
    foco: ['Bíceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-maquina.jpg',
      alt: 'Rosca maquina',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/yIIgcVRkzus' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 23,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '7. Rosca polia corda',
    foco: ['Bíceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-polia-corda.webp',
      alt: 'Rosca polia corda',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/1lR_dT07wBM' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 24,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '8. Rosca martelo alternado',
    foco: ['Bíceps'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/rosca-martelo-alternado.webp',
      alt: 'Rosca martelo alternado',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/ITRfzXEcBz0' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 25,
    treino: 'Costas e Bíceps',
    nome: 'Treino 2B',
    exercicio: '9. Bike horizontal',
    foco: ['Aeróbico'],
    series: 0,
    repeticoes: 0,
    carga: '10 minutos',
    imagem: {
      src: '',
      alt: '',
    },
    video: '',
    obs: '',
  },
  {
    id: 26,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '1. Bike vertical',
    foco: ['Aeróbico'],
    series: 0,
    repeticoes: 0,
    carga: '10 minutos',
    imagem: {
      src: '',
      alt: '',
    },
    video: '',
    obs: '',
  },
  {
    id: 27,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '2. Arnold combinado',
    foco: ['Ombros', 'Tríceps'],
    series: 3,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/arnold-combinado.webp',
      alt: 'Arnold combinado',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/DDBnx9vB85E' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 28,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '3. Elevação lateral halteres combinado',
    foco: ['Ombros', 'Tríceps'],
    series: 4,
    repeticoes: 10,
    carga: '1',
    imagem: {
      src: '../../assets/elevação-lateral-halteres-combinado.jpg',
      alt: 'Arnold combinado',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/U85S1RLdxtI' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 29,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '4. Elevação frontal anilha',
    foco: ['Ombros', 'Tríceps'],
    series: 4,
    repeticoes: 10,
    carga: '1',
    imagem: {
      src: '../../assets/elevação-frontal-anilha.jpg',
      alt: 'Elevação frontal anilha',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/KmOt4iYOmmE' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 30,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '5. Abd edge',
    foco: ['Abdómen'],
    series: 4,
    repeticoes: 12,
    carga: '1',
    imagem: {
      src: '../../assets/abd-edge.jpg',
      alt: 'Elevação frontal anilha',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/CbkL1bFZcqE' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
  {
    id: 31,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '6. Abd infra paralela',
    foco: ['Abdómen'],
    series: 4,
    repeticoes: 10,
    carga: '1',
    imagem: {
      src: '../../assets/abd-infra-paralela.jpg',
      alt: 'Elevação frontal anilha',
    },
    video: '',
    obs: '',
  },
  {
    id: 32,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '7. Abd prancha isometria',
    foco: ['Abdómen'],
    series: 4,
    repeticoes: 0,
    carga: '40 segundos',
    imagem: {
      src: '../../assets/abd-prancha-isometria.jpg',
      alt: 'Abd prancha isometria',
    },
    video: '',
    obs: '',
  },
  {
    id: 33,
    treino: 'Ombros, Tríceps e Abdómen',
    nome: 'Treino 2C',
    exercicio: '8. Desenvolvimento máquina',
    foco: ['Ombros', 'Tríceps'],
    series: 3,
    repeticoes: 15,
    carga: '',
    imagem: {
      src: '../../assets/desenvolvimento-maquina.png',
      alt: 'Desenvolvimento máquina',
    },
    video:
      "<iframe width='360' height='203' src='https://www.youtube.com/embed/89yUaLoRcko' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
    obs: '',
  },
];
